repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']

# -   repo: https://github.com/pycqa/isort
#     rev: 5.12.0
#     hooks:
#     -   id: isort

# -   repo: https://github.com/psf/black
#     rev: 23.3.0
#     hooks:
#     -   id: black

# -   repo: https://github.com/pycqa/flake8
#     rev: 6.0.0
#     hooks:
#     -   id: flake8
#         additional_dependencies: [flake8-docstrings]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.3.0
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-all]
#         exclude: ^tests/
