version: "3.9"
services:
  eznlp-dev:
    image: pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel

    network_mode: host
    ipc: host
    shm_size: 32g
    runtime: nvidia

    # For GPU usage and profiling
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - seccomp:unconfined

    # Delete this section if you don't have a GPU.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
